    const data = [
        {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'breakfast',
        price: 15.99,
        img: 'https://media.istockphoto.com/id/1148638351/fr/photo/petit-d%C3%A9jeuner-du-dimanche.jpg?s=612x612&w=0&k=20&c=8W1JpqdmNYejO0LpNfw3_dmo0YKCIFzzQYmGN2Q33CQ=',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
        },
        {
        id: 2,
        title: 'diner double',
        category: 'lunch',
        price: 13.99,
        img: 'https://image.shutterstock.com/image-photo/sandwich-ham-cheese-tomatoes-lettuce-260nw-1027873330.jpg',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
        },
        {
        id: 3,
        title: 'godzilla milkshake',
        category: 'shakes',
        price: 6.99,
        img: 'https://media.istockphoto.com/id/1311373994/fr/photo/le-lait-tremble-dans-des-tasses-en-plastique-et-des-pailles-sur-une-table-en-bois-fonc%C3%A9.jpg?s=612x612&w=0&k=20&c=YFx0pNthTrSSqgzNLsI51sKyFE6vPO_RtKxq3NYy55Y=',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
        },
        {
        id: 4,
        title: 'country delight',
        category: 'breakfast',
        price: 20.99,
        img: 'https://t4.ftcdn.net/jpg/00/49/57/65/360_F_49576555_YQlnmwVJVMubeii9g7yqpunlgjqKKx3i.jpg',
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
        },
        {
        id: 5,
        title: 'egg attack',
        category: 'lunch',
        price: 22.99,
        img: 'https://img.freepik.com/photos-gratuite/vue-dessus-pizza-au-pepperoni-coupee-six-tranches_141793-2157.jpg?w=2000',
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
        },
        {
        id: 6,
        title: 'oreo dream',
        category: 'shakes',
        price: 18.99,
        img: 'https://media.istockphoto.com/id/486091503/fr/photo/milkshake-avec-du-cookie-et-chapelure.jpg?s=612x612&w=0&k=20&c=TDIxMRez-gmzzfLydFgxa5o2oIIsGPn1TqTjJSyah-s=',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
        },
        {
        id: 7,
        title: 'bacon overflow',
        category: 'breakfast',
        price: 8.99,
        img: 'https://media.istockphoto.com/id/157610681/fr/photo/tarte-aux-fruits.jpg?s=612x612&w=0&k=20&c=JDQpDA2kDUp0HoYZPlgaT-DGDVEg-0B9YHlzjMr5Vi4=',
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
        },
        {
        id: 8,
        title: 'american classic',
        category: 'lunch',
        price: 12.99,
        img: 'https://previews.123rf.com/images/kovalnadiya/kovalnadiya2111/kovalnadiya211100348/192854328-canard-de-no%C3%ABl-farci-r%C3%B4ti-traditionnel-avec-du-romarin-et-des-oranges-sur-fond-de-bois-vue-de-dessus.jpg',
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
        },
        {
        id: 9,
        title: 'quarantine buddy',
        category: 'shakes',
        price: 16.99,
        img: 'https://media.gettyimages.com/id/1126893721/fr/photo/faibles-cl%C3%A9s-smoothies-au-chocolat-sur-une-table-dans-une-cuisine-rustique.jpg?s=612x612&w=gi&k=20&c=jemfHBPU429Q7EBXPv8nn487aBp7AwPGFdq8oZgXqe4=',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
        },
    ];
    export default data;